name: CI

on:
  push:
    paths:
      - '**.cairo'

env:
  LINK: https://github.com/software-mansion/scarb/releases/download/v0.4.0/scarb-v0.4.0-x86_64-unknown-linux-gnu.tar.gz
  NAME: scarb-v0.4.0-x86_64-unknown-linux-gnu

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3
      - name: Download binaries
        run: curl -L -o $NAME.tar.gz $LINK
      - name: Prepare binaries
        run: tar -xvf $NAME
      - name: Make binaries available
        run: echo "./$NAME/bin" >> $GITHUB_PATH
      - name: Check formatting
        run: scarb fmt --check
      - name: Build with scarb
        run: scarb build
